version: "3.8"

services:
  ktor-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ktor-trial:latest
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      JDBC_URL: "jdbc:mysql://ktor-trial-db:3316/ktor_trial?allowPublicKeyRetrieval=true&useSSL=false"
      PORT: "8080"
  ktor-trial-db:
    container_name: trial_db
    image: mysql:8.0.33
    build:
      # setting parent directory as context to read files in other directory
      context: .
      dockerfile: docker/ktor_trial_db/Dockerfile
    ports:
      - "3316:3316"
    environment:
      MYSQL_DATABASE: ktor_trial
      MYSQL_USER: test_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_TCP_PORT: 3316
      TZ: "Asia/Tokyo"
    # comment in bellow to change user group and avoid error in windows docker-tools
    # command: bash -c 'usermod -o -u 1000 mysql; groupmod -o -g 500 mysql; chown -R mysql:root /var/run/mysqld/; /entrypoint.sh mysqld --user=mysql --console'
    volumes:
      - ./docker/ktor_trial_db/db:/var/lib/mysql
  test-db:
    container_name: test_db
    image: mysql:8.0.33
    build:
      # setting parent directory as context to read files in other directory
      context: ../
      dockerfile: docker/test_db/Dockerfile
    ports:
      - "3317:3317"
    environment:
      MYSQL_DATABASE: ktor_trial
      MYSQL_USER: test_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_TCP_PORT: 3317
      TZ: "Asia/Tokyo"
    # comment in bellow to change user group and avoid error in windows docker-tools
    # command: bash -c 'usermod -o -u 1000 mysql; groupmod -o -g 500 mysql; chown -R mysql:root /var/run/mysqld/; /entrypoint.sh mysqld --user=mysql --console'
    volumes:
      - ./docker/test_db/db:/var/lib/mysql
