ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
trial:
    database:
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: "jdbc:mysql://localhost:3316/ktor_trial?allowPublicKeyRetrieval=true&useSSL=false"
        userName: test_user
        password: password
        cloudSqlInstanceName: ""
        maximumPoolSize: 80
        isAutoCommit: false
        transactionIsolation: TRANSACTION_REPEATABLE_READ
        maxLifetime: 20000000
        idleTimeOut: 60000
        minimumIdle: 10