name: CI Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test with MySQL 8.4
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.4.4
        ports:
          - 3317:3306
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Migrate Test DB
        run: ./gradlew flywayMigrateTestDB

      - name: Clean build artifacts
        run: ./gradlew clean

      - name: Build with Gradle
        run: ./gradlew :infrastructure:build --no-daemon
        env:
          IS_OPENTELEMETRY_READY: "false"
