name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # mainブランチに push されたときに実行

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    # 必要なパーミッション（id-token は Cloud Run のデプロイで必要）
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLECLOUD_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLECLOUD_PROJECT_ID }}

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GOOGLECLOUD_PROJECT_ID }}/ktor-trial:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.GOOGLECLOUD_PROJECT_ID }}/ktor-trial:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          image: gcr.io/${{ secrets.GOOGLECLOUD_PROJECT_ID }}/ktor-trial:${{ github.sha }}
          service: ktor-trial           # Cloud Run 上のサービス名
          region: asia-northeast1     # 例：東京リージョン。適宜変更してください
